# CircleCI 2.0 Configuration File
version: 2.1
jobs:
  push-master:
    docker:
      - image: circleci/classic:latest
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            echo 'Circleci'

  push-qa:
    docker:
      - image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'

  push-tag:
    docker:
      - image: circleci/classic:latest
    steps:
      - run:
          name: Tag e Execute Processos
          command: |
            echo 'TAGS RUNNING ....'


workflows:
  version: 2
  push-deploy:
    jobs:
      - push-master:
          filters:
            branches:
              only: master
      - push-qa:
          filters:
            branches:
              ignore:
                - master

  push-tag:
    jobs:
      - push-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)+(-\D+)*/